apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - server-deployment.yaml
  - client-deployment.yaml

namespace: k8s-graceful-shutdown-test
