apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: k8s-graceful-shutdown-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ghcr.io/donileongdeepernetwork/k8s-graceful-shutdown-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["/app/server"]
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
